#!/bin/sh

# startup script for fixing network interfaces...

DESC="fix_inet"
NAME=fix_inet

. /lib/lsb/init-functions

# figure out where we are actually at...
REALPATH=`readlink -f "$0"`
BASEDIR=`dirname $REALPATH`/..

case "$1" in
    start)
        log_daemon_msg "Resetting network interfaces" $NAME
        "$BASEDIR/network/fix_inet"
        log_end_msg $?
    ;;

    stop)
        log_daemon_msg "Stop" $NAME
        log_end_msg 0
    ;;

    restart)
        $0 stop
        $0 start
    ;;

    reload|force-reload)
        log_daemon_msg "Reload" $NAME
        log_end_msg 0
    ;;

    *)
        log_action_msg "Usage: $NAME {start|stop|status|restart|reload|force-reload}"
        exit 2
esac
exit 0

