#!/bin/sh

# Often, the WiFi adapter does not come up on boot and the USB network
# interfaces cause routing problems.  This script will reset the WiFi
# interface and disable the USB interfaces.

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="fix_inet"
NAME=fix_inet

. /lib/lsb/init-functions

safe_ifdown() {
  IFACE=$1
  STAT=`ifconfig -s | grep $IFACE`
  if [ -n "$STAT" ] ; then
    ifconfig $IFACE down
  fi
}

safe_ifup() {
  IFACE=$1
  STAT=`ifconfig -s | grep $IFACE`
  if [ -z "$STAT" ] ; then
    ifconfig $IFACE up
  fi
}

case "$1" in
    start)
        log_daemon_msg "Resetting network interfaces" $NAME

        connmanctl disable wifi > /dev/null
        safe_ifdown usb0
        safe_ifdown usb1

        connmanctl enable wifi > /dev/null
        safe_ifup wlan0

        log_end_msg $?
    ;;

    stop)
        log_daemon_msg "Stop" $NAME
        log_end_msg 0
    ;;

    restart)
        $0 stop
        $0 start
    ;;

    reload|force-reload)
        log_daemon_msg "Reload" $NAME
        log_end_msg 0
    ;;

    *)
        log_action_msg "Usage: $NAME {start|stop|status|restart|reload|force-reload}"
        exit 2
esac
exit 0

